<?php

use Illuminate\Database\Seeder;

class DataRowsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('data_rows')->delete();
        
        \DB::table('data_rows')->insert(array (
            0 => 
            array (
                'id' => 1,
                'data_type_id' => 1,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            1 => 
            array (
                'id' => 2,
                'data_type_id' => 1,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 2,
            ),
            2 => 
            array (
                'id' => 3,
                'data_type_id' => 1,
                'field' => 'email',
                'type' => 'text',
                'display_name' => 'Email',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 3,
            ),
            3 => 
            array (
                'id' => 4,
                'data_type_id' => 1,
                'field' => 'password',
                'type' => 'password',
                'display_name' => 'Password',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{}',
                'order' => 4,
            ),
            4 => 
            array (
                'id' => 5,
                'data_type_id' => 1,
                'field' => 'remember_token',
                'type' => 'text',
                'display_name' => 'Remember Token',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 5,
            ),
            5 => 
            array (
                'id' => 6,
                'data_type_id' => 1,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"format":"%d-%m-%Y"}',
                'order' => 6,
            ),
            6 => 
            array (
                'id' => 7,
                'data_type_id' => 1,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"format":"%d-%m-%Y"}',
                'order' => 7,
            ),
            7 => 
            array (
                'id' => 8,
                'data_type_id' => 1,
                'field' => 'avatar',
                'type' => 'image',
                'display_name' => 'Avatar',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 8,
            ),
            8 => 
            array (
                'id' => 9,
                'data_type_id' => 1,
                'field' => 'user_belongsto_role_relationship',
                'type' => 'relationship',
                'display_name' => 'Role',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsTo","column":"role_id","key":"id","label":"display_name","pivot_table":"roles","pivot":"0","taggable":"0"}',
                'order' => 10,
            ),
            9 => 
            array (
                'id' => 10,
                'data_type_id' => 1,
                'field' => 'user_belongstomany_role_relationship',
                'type' => 'relationship',
                'display_name' => 'Roles',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsToMany","column":"id","key":"id","label":"display_name","pivot_table":"user_roles","pivot":"1","taggable":"0"}',
                'order' => 11,
            ),
            10 => 
            array (
                'id' => 11,
                'data_type_id' => 1,
                'field' => 'settings',
                'type' => 'hidden',
                'display_name' => 'Settings',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 12,
            ),
            11 => 
            array (
                'id' => 12,
                'data_type_id' => 2,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            12 => 
            array (
                'id' => 13,
                'data_type_id' => 2,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            13 => 
            array (
                'id' => 14,
                'data_type_id' => 2,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 3,
            ),
            14 => 
            array (
                'id' => 15,
                'data_type_id' => 2,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 4,
            ),
            15 => 
            array (
                'id' => 16,
                'data_type_id' => 3,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            16 => 
            array (
                'id' => 17,
                'data_type_id' => 3,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            17 => 
            array (
                'id' => 18,
                'data_type_id' => 3,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 3,
            ),
            18 => 
            array (
                'id' => 19,
                'data_type_id' => 3,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 4,
            ),
            19 => 
            array (
                'id' => 20,
                'data_type_id' => 3,
                'field' => 'display_name',
                'type' => 'text',
                'display_name' => 'Display Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 5,
            ),
            20 => 
            array (
                'id' => 21,
                'data_type_id' => 1,
                'field' => 'role_id',
                'type' => 'text',
                'display_name' => 'Role',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 9,
            ),
            21 => 
            array (
                'id' => 56,
                'data_type_id' => 7,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            22 => 
            array (
                'id' => 57,
                'data_type_id' => 7,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Nome',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required"}}',
                'order' => 2,
            ),
            23 => 
            array (
                'id' => 58,
                'data_type_id' => 7,
                'field' => 'document',
                'type' => 'text',
                'display_name' => 'RG',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required"}}',
                'order' => 4,
            ),
            24 => 
            array (
                'id' => 59,
                'data_type_id' => 7,
                'field' => 'cpf',
                'type' => 'text',
                'display_name' => 'Cpf',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required"}}',
                'order' => 5,
            ),
            25 => 
            array (
                'id' => 60,
                'data_type_id' => 7,
                'field' => 'status',
                'type' => 'select_dropdown',
                'display_name' => 'Status',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"options":{"ativo":"Ativo","inativo":"Inativo"}}',
                'order' => 6,
            ),
            26 => 
            array (
                'id' => 61,
                'data_type_id' => 7,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Registrado em',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"format":"%d\\/%m\\/%Y"}',
                'order' => 14,
            ),
            27 => 
            array (
                'id' => 62,
                'data_type_id' => 7,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Atualizado em',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"format":"%d\\/%m\\/%Y"}',
                'order' => 15,
            ),
            28 => 
            array (
                'id' => 63,
                'data_type_id' => 7,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"format":"%d\\/%m\\/%Y"}',
                'order' => 16,
            ),
            29 => 
            array (
                'id' => 64,
                'data_type_id' => 8,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            30 => 
            array (
                'id' => 65,
                'data_type_id' => 8,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 2,
            ),
            31 => 
            array (
                'id' => 66,
                'data_type_id' => 8,
                'field' => 'cpf',
                'type' => 'text',
                'display_name' => 'Cpf',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 3,
            ),
            32 => 
            array (
                'id' => 67,
                'data_type_id' => 8,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 4,
            ),
            33 => 
            array (
                'id' => 68,
                'data_type_id' => 8,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 5,
            ),
            34 => 
            array (
                'id' => 69,
                'data_type_id' => 8,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 6,
            ),
            35 => 
            array (
                'id' => 70,
                'data_type_id' => 8,
                'field' => 'status',
                'type' => 'checkbox',
                'display_name' => 'Status',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{}',
                'order' => 7,
            ),
            36 => 
            array (
                'id' => 81,
                'data_type_id' => 1,
                'field' => 'user_hasmany_customer_relationship',
                'type' => 'relationship',
                'display_name' => 'customers',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"model":"App\\\\Customer","table":"customers","type":"hasMany","column":"user_id","key":"id","label":"name","pivot_table":"categories","pivot":"0","taggable":"0"}',
                'order' => 13,
            ),
            37 => 
            array (
                'id' => 82,
                'data_type_id' => 7,
                'field' => 'user_id',
                'type' => 'select_dropdown',
                'display_name' => 'Usuário',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"relationship":{"key":"id","label":"name","scopes":["active"]}}',
                'order' => 7,
            ),
            38 => 
            array (
                'id' => 83,
                'data_type_id' => 1,
                'field' => 'email_verified_at',
                'type' => 'timestamp',
                'display_name' => 'Email Verified At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 6,
            ),
            39 => 
            array (
                'id' => 90,
                'data_type_id' => 11,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            40 => 
            array (
                'id' => 91,
                'data_type_id' => 11,
                'field' => 'class_date_time',
                'type' => 'timestamp',
                'display_name' => 'Data/Hora',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 3,
            ),
            41 => 
            array (
                'id' => 92,
                'data_type_id' => 11,
                'field' => 'room',
                'type' => 'text',
                'display_name' => 'Sala',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 4,
            ),
            42 => 
            array (
                'id' => 93,
                'data_type_id' => 11,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Criado em',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 6,
            ),
            43 => 
            array (
                'id' => 94,
                'data_type_id' => 11,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Atualizado em',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 7,
            ),
            44 => 
            array (
                'id' => 95,
                'data_type_id' => 11,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 8,
            ),
            45 => 
            array (
                'id' => 96,
                'data_type_id' => 11,
                'field' => 'title',
                'type' => 'text',
                'display_name' => 'Aula de',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 2,
            ),
            46 => 
            array (
                'id' => 97,
                'data_type_id' => 11,
                'field' => 'description',
                'type' => 'text',
                'display_name' => 'Descrição',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 9,
            ),
            47 => 
            array (
                'id' => 98,
                'data_type_id' => 12,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            48 => 
            array (
                'id' => 99,
                'data_type_id' => 12,
                'field' => 'customer_id',
                'type' => 'select_dropdown',
                'display_name' => 'Customer Id',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 2,
            ),
            49 => 
            array (
                'id' => 100,
                'data_type_id' => 12,
                'field' => 'group_class_id',
                'type' => 'select_dropdown',
                'display_name' => 'Group Class Id',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 3,
            ),
            50 => 
            array (
                'id' => 101,
                'data_type_id' => 12,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 4,
            ),
            51 => 
            array (
                'id' => 102,
                'data_type_id' => 12,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 5,
            ),
            52 => 
            array (
                'id' => 103,
                'data_type_id' => 12,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 1,
                'details' => '{}',
                'order' => 6,
            ),
            53 => 
            array (
                'id' => 161,
                'data_type_id' => 27,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            54 => 
            array (
                'id' => 162,
                'data_type_id' => 27,
                'field' => 'total',
                'type' => 'number',
                'display_name' => 'Total',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"min":0,"validation":{"rule":"required"}}',
                'order' => 6,
            ),
            55 => 
            array (
                'id' => 163,
                'data_type_id' => 27,
                'field' => 'plan_date_start',
                'type' => 'date',
                'display_name' => 'Data início do plano',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"format":"%d\\/%m\\/%Y","validation":{"rule":"required"}}',
                'order' => 4,
            ),
            56 => 
            array (
                'id' => 164,
                'data_type_id' => 27,
                'field' => 'plan_date_end',
                'type' => 'date',
                'display_name' => 'Data vencimento do plano',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"format":"%d\\/%m\\/%Y","validation":{"rule":"required"}}',
                'order' => 5,
            ),
            57 => 
            array (
                'id' => 166,
                'data_type_id' => 27,
                'field' => 'status',
                'type' => 'select_dropdown',
                'display_name' => 'Situação Plano',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"options":{"adimplente":"Adimplente","inadimplente":"Inadimplente"}}',
                'order' => 7,
            ),
            58 => 
            array (
                'id' => 167,
                'data_type_id' => 27,
                'field' => 'customer_id',
                'type' => 'select_dropdown',
                'display_name' => 'Cliente',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"relationship":{"key":"id","label":"name","scopes":["active"]},"validation":{"rule":"required"}}',
                'order' => 2,
            ),
            59 => 
            array (
                'id' => 168,
                'data_type_id' => 27,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Feito em',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"format":"%d\\/%m\\/%Y %H:%M"}',
                'order' => 9,
            ),
            60 => 
            array (
                'id' => 169,
                'data_type_id' => 27,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Atualizado em',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"format":"%d\\/%m\\/%Y"}',
                'order' => 10,
            ),
            61 => 
            array (
                'id' => 170,
                'data_type_id' => 27,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deletado em',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"format":"%d\\/%m\\/%Y"}',
                'order' => 11,
            ),
            62 => 
            array (
                'id' => 171,
                'data_type_id' => 27,
                'field' => 'payment_belongsto_customer_relationship',
                'type' => 'relationship',
                'display_name' => 'Cliente',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Customer","table":"customers","type":"belongsTo","column":"customer_id","key":"id","label":"name","pivot_table":"categories","pivot":"0","taggable":"0"}',
                'order' => 3,
            ),
            63 => 
            array (
                'id' => 173,
                'data_type_id' => 7,
                'field' => 'address',
                'type' => 'text',
                'display_name' => 'Endereço de residência',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 9,
            ),
            64 => 
            array (
                'id' => 174,
                'data_type_id' => 7,
                'field' => 'number',
                'type' => 'text',
                'display_name' => 'Número',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 10,
            ),
            65 => 
            array (
                'id' => 175,
                'data_type_id' => 7,
                'field' => 'postalcode',
                'type' => 'text',
                'display_name' => 'CEP',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 8,
            ),
            66 => 
            array (
                'id' => 176,
                'data_type_id' => 7,
                'field' => 'state',
                'type' => 'select_dropdown',
                'display_name' => 'Estado',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"options":{"":"","AC":"Acre","AL":"Alagoas","AP":"Amap\\u00e1","AM":"Amazonas","BA":"Bahia","CE":"Cear\\u00e1","DF":"Distrito Federal","ES":"Esp\\u00edrito Santo","GO":"Goi\\u00e1s","MA":"Maranh\\u00e3o","MT":"Mato Grosso","MS":"Mato Grosso do Sul","MG":"Minas Gerais","PA":"Par\\u00e1","PB":"Para\\u00edba","PR":"Paran\\u00e1","PE":"Pernambuco","PI":"Piau\\u00ed","RJ":"Rio de Janeiro","RN":"Rio Grande do Norte","RS":"Rio Grande do Sul","RO":"Rond\\u00f4nia","RR":"Roraima","SC":"Santa Catarina","SP":"S\\u00e3o Paulo","SE":"Sergipe","TO":"Tocantins"}}',
                'order' => 12,
            ),
            67 => 
            array (
                'id' => 177,
                'data_type_id' => 7,
                'field' => 'city',
                'type' => 'text',
                'display_name' => 'Cidade',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required"}}',
                'order' => 13,
            ),
            68 => 
            array (
                'id' => 178,
                'data_type_id' => 7,
                'field' => 'register_code',
                'type' => 'text',
                'display_name' => 'Código Matricula',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 3,
            ),
            69 => 
            array (
                'id' => 179,
                'data_type_id' => 7,
                'field' => 'district',
                'type' => 'text',
                'display_name' => 'Bairro',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 11,
            ),
            70 => 
            array (
                'id' => 180,
                'data_type_id' => 28,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 2,
            ),
            71 => 
            array (
                'id' => 181,
                'data_type_id' => 28,
                'field' => 'date_starts',
                'type' => 'date',
                'display_name' => 'Data Início',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"format":"%d\\/%m\\/%y"}',
                'order' => 3,
            ),
            72 => 
            array (
                'id' => 182,
                'data_type_id' => 28,
                'field' => 'date_ends',
                'type' => 'date',
                'display_name' => 'Data Fim',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"format":"%d\\/%m\\/%y"}',
                'order' => 4,
            ),
            73 => 
            array (
                'id' => 183,
                'data_type_id' => 28,
                'field' => 'days_remaining',
                'type' => 'number',
                'display_name' => 'Dias Restantes',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 5,
            ),
            74 => 
            array (
                'id' => 184,
                'data_type_id' => 28,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"format":"%d\\/%m\\/%y"}',
                'order' => 7,
            ),
            75 => 
            array (
                'id' => 185,
                'data_type_id' => 28,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"format":"%d\\/%m\\/%y"}',
                'order' => 8,
            ),
            76 => 
            array (
                'id' => 186,
                'data_type_id' => 28,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 9,
            ),
            77 => 
            array (
                'id' => 187,
                'data_type_id' => 28,
                'field' => 'status',
                'type' => 'select_dropdown',
                'display_name' => 'Status',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"options":{"ativo":"Ativo","inativo":"Inativo"}}',
                'order' => 6,
            ),
            78 => 
            array (
                'id' => 190,
                'data_type_id' => 27,
                'field' => 'plan_type',
                'type' => 'select_dropdown',
                'display_name' => 'Plano',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"options":{"mensal":"Mensal","anual":"Anual"}}',
                'order' => 8,
            ),
            79 => 
            array (
                'id' => 191,
                'data_type_id' => 7,
                'field' => 'customer_belongsto_user_relationship',
                'type' => 'relationship',
                'display_name' => 'users',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"app\\\\User","table":"users","type":"belongsTo","column":"id","key":"id","label":"id","pivot_table":"categories","pivot":"0","taggable":"0"}',
                'order' => 17,
            ),
            80 => 
            array (
                'id' => 192,
                'data_type_id' => 11,
                'field' => 'group_class_belongsto_instructor_relationship',
                'type' => 'relationship',
                'display_name' => 'Instrutor/a',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Instructor","table":"instructors","type":"belongsTo","column":"instructor_id","key":"id","label":"name","pivot_table":"categories","pivot":"0","taggable":"0"}',
                'order' => 5,
            ),
            81 => 
            array (
                'id' => 193,
                'data_type_id' => 29,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 2,
            ),
            82 => 
            array (
                'id' => 194,
                'data_type_id' => 29,
                'field' => 'anamnese_patient',
                'type' => 'text',
                'display_name' => 'Anamnese Paciente',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 3,
            ),
            83 => 
            array (
                'id' => 195,
                'data_type_id' => 29,
                'field' => 'skinfolds',
                'type' => 'text',
                'display_name' => 'Dobras Cutaneas',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 4,
            ),
            84 => 
            array (
                'id' => 196,
                'data_type_id' => 29,
                'field' => 'exercise_test',
                'type' => 'text',
                'display_name' => 'Exame Ergometrico',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 5,
            ),
            85 => 
            array (
                'id' => 197,
                'data_type_id' => 29,
                'field' => 'evaluation_date',
                'type' => 'date',
                'display_name' => 'Data Avaliação',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 6,
            ),
            86 => 
            array (
                'id' => 198,
                'data_type_id' => 29,
                'field' => 'next_evaluation_date',
                'type' => 'date',
                'display_name' => 'Data Próxima Avaliação',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 7,
            ),
            87 => 
            array (
                'id' => 199,
                'data_type_id' => 29,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Criado em',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => '{}',
                'order' => 8,
            ),
            88 => 
            array (
                'id' => 200,
                'data_type_id' => 29,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Atualizado em',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 9,
            ),
            89 => 
            array (
                'id' => 201,
                'data_type_id' => 29,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deletado em',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 10,
            ),
            90 => 
            array (
                'id' => 202,
                'data_type_id' => 29,
                'field' => 'customer_id',
                'type' => 'text',
                'display_name' => 'Cliente',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 1,
            ),
            91 => 
            array (
                'id' => 203,
                'data_type_id' => 12,
                'field' => 'customers_has_group_class_belongsto_customer_relationship',
                'type' => 'relationship',
                'display_name' => 'customers',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Customer","table":"customers","type":"belongsTo","column":"customer_id","key":"id","label":"name","pivot_table":"categories","pivot":"0","taggable":"0"}',
                'order' => 7,
            ),
            92 => 
            array (
                'id' => 204,
                'data_type_id' => 12,
                'field' => 'customers_has_group_class_belongsto_group_class_relationship',
                'type' => 'relationship',
                'display_name' => 'group_classes',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\GroupClass","table":"group_classes","type":"belongsTo","column":"group_class_id","key":"id","label":"title","pivot_table":"categories","pivot":"0","taggable":"0"}',
                'order' => 8,
            ),
            93 => 
            array (
                'id' => 205,
                'data_type_id' => 12,
                'field' => 'customers_has_group_class_hasone_instructor_relationship',
                'type' => 'relationship',
                'display_name' => 'instructors',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Instructor","table":"instructors","type":"hasOne","column":"id","key":"id","label":"id","pivot_table":"categories","pivot":"0","taggable":null}',
                'order' => 9,
            ),
            94 => 
            array (
                'id' => 206,
                'data_type_id' => 11,
                'field' => 'instructor_id',
                'type' => 'text',
                'display_name' => 'Instructor Id',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 10,
            ),
            95 => 
            array (
                'id' => 207,
                'data_type_id' => 8,
                'field' => 'instructor_hasone_user_relationship',
                'type' => 'relationship',
                'display_name' => 'users',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"app\\\\User","table":"users","type":"hasOne","column":"id","key":"id","label":"id","pivot_table":"categories","pivot":"0","taggable":null}',
                'order' => 8,
            ),
            96 => 
            array (
                'id' => 208,
                'data_type_id' => 28,
                'field' => 'customer_id',
                'type' => 'text',
                'display_name' => 'Customer Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 10,
            ),
            97 => 
            array (
                'id' => 209,
                'data_type_id' => 28,
                'field' => 'vacation_hasone_customer_relationship',
                'type' => 'relationship',
                'display_name' => 'Cliente',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Customer","table":"customers","type":"hasOne","column":"id","key":"id","label":"name","pivot_table":"categories","pivot":"0","taggable":"0"}',
                'order' => 1,
            ),
        ));
        
        
    }
}